-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

-- This is an example Hyprland Lua config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can (and should!!) split this configuration into multiple files
-- Create your files separately and then require them like this:
-- require("myColors")

-- ── Local machine settings ──────────────────────────────────────────────────
-- ~/.local_host_settings lives OUTSIDE the repo (gitignored / never committed).
-- Each machine has its own copy; the installer creates it from the template the
-- very first time and never overwrites it again.  Edit it + hyprctl reload.
-- Missing keys fall back to the hardcoded defaults below so the config still
-- works even without the file.
-- ─────────────────────────────────────────────────────────────────────────────

local function read_settings()
  local s = {}
  local path = os.getenv("HOME") .. "/.local_host_settings"
  local f = io.open(path, "r")
  if not f then return s end
  for raw in f:lines() do
    local line = raw:match("^%s*(.-)%s*$")
    if line ~= "" and not line:match("^#") then
      local k, v = line:match("^(.-)=(.*)$")
      if k then
        k = k:match("^%s*(.-)%s*$")
        v = v:match("^%s*(.-)%s*$")
        s[k] = v
      end
    end
  end
  f:close()
  return s
end

local _cfg = read_settings()

local function settings(key, default)
  local v = _cfg[key]
  if v and v ~= "" then return v end
  return default
end

local function settings_bool(key, default)
  local v = _cfg[key]
  if v then
    v = v:lower()
    if v == "true"  or v == "1" or v == "yes" then return true  end
    if v == "false" or v == "0" or v == "no"  then return false end
  end
  return default
end

local function settings_num(key, default)
  local v = _cfg[key]
  if v and v ~= "" then
    local n = tonumber(v)
    if n then return n end
  end
  return default
end

------------------
---- MONITORS ----
------------------

-- See https://wiki.hypr.land/Configuring/Basics/Monitors/
hl.monitor(
  {
    output = settings("PRIMARY_MONITOR", "eDP-1"),
    mode = settings("PRIMARY_MODE", "preferred"),
    position = "auto",
    scale = settings_num("PRIMARY_SCALE", 1.5),
  }
)

-- Perfiles de monitores por identidad EDID, no por puerto: se matchean
-- con 'desc:' y no con el nombre del cable, así un mismo monitor enchufado a
-- DP-1, USB-C o HDMI-A-1 siempre recibe su resolución/escala/posición. Aplica
-- tanto a externos como al panel INTERNO (eDP-1): si le guardás un perfil, gana
-- sobre PRIMARY_MODE/PRIMARY_SCALE de ~/.local_host_settings. La lista vive en
-- ~/.local_host_monitors (AFUERA del repo, mismo modelo que ~/.local_host_settings:
-- el instalador copia templates/local_host_monitors la primera vez y nunca vuelve
-- a pisarla). Si el archivo falta, cae en los defaults de abajo y el config igual
-- funciona. El perfil 'fallback' cubre cualquier monitor sin perfil propio,
-- incluido uno NUEVO recién conectado. Agregar un monitor: enchuflo, 'monitor-id',
-- pegar el bloque, reload.
local function load_monitors()
  local path = os.getenv("HOME") .. "/.local_host_monitors"
  local f = io.open(path, "r")
  if f then
    f:close()
    return dofile(path)
  end
  return { fallback = { mode = "preferred", position = "auto-right", scale = 1 }, external = {} }
end

local monitors = load_monitors()

hl.monitor({
  output = "",
  mode = monitors.fallback.mode,
  position = monitors.fallback.position,
  scale = monitors.fallback.scale,
})

for _, monitor in ipairs(monitors.external) do
  local rule = { output = monitor.desc }
  if monitor.disabled then
    -- a disabled profile keeps the port off; mode/position/scale are moot
    rule.disabled = true
  else
    rule.mode = monitor.mode
    rule.position = monitor.position
    rule.scale = monitor.scale
    if monitor.transform and monitor.transform ~= 0 then
      rule.transform = monitor.transform
    end
    if monitor.mirror and monitor.mirror ~= "" then
      rule.mirror = monitor.mirror
    end
  end
  hl.monitor(rule)

  -- workspaces owned by this monitor (EDID-matched, so they follow the monitor
  -- across ports). Only when the monitor is actually enabled.
  if not monitor.disabled then
    for _, ws in ipairs(monitor.workspaces or {}) do
      hl.workspace_rule({ workspace = ws, monitor = monitor.desc })
    end
  end
end

---------------------
---- MY PROGRAMS ----
---------------------

-- Set programs that you use
local terminal = "foot"
local fileManager = "thunar"
local launcher = "rofi -show drun -show-icons"
local runner = "rofi -show run"
local bar = "waybar"
local browser = "firefox"

-- Capturas de pantalla (los binds están más abajo, junto a la tecla Print).
--
-- Notas comunes a todos:
--   -z / --freeze     congela la imagen al iniciar la selección. Sin esto no se
--                     pueden capturar menús desplegados ni tooltips: desaparecen
--                     apenas movés el mouse para seleccionar.
--   --clipboard-only  hyprshot por defecto guarda en disco Y copia; esta opción
--                     evita llenar ~/Pictures con capturas descartables.
--   -m active         requiere repetir --mode con la selección buscada
--                     (window o output), es la sintaxis que pide hyprshot.

-- Print: región, anotar en satty, y al portapapeles.
--   --copy-command wl-copy   satty NO sabe copiar en Wayland por su cuenta; sin
--                            esta opción el botón de copiar no hace nada.
--   --actions-on-enter ...   Enter copia, sin tener que buscar el botón.
--   --early-exit copy        cierra satty apenas copió, en vez de quedar abierto.
local screenshot = "hyprshot -m region -z --raw | satty --filename - "
    .. "--copy-command wl-copy --actions-on-enter save-to-clipboard --early-exit copy"

-- SHIFT + Print: región directo al portapapeles, sin pasar por satty.
local screenshotCopy = "hyprshot -m region -z --clipboard-only"

-- CONTROL + Print: región a ~/Pictures/screenshots, y la RUTA del archivo (no la
-- imagen) al portapapeles. hyprshot no tiene una opción para eso (siempre copia la
-- imagen cuando guarda a disco), así que usa un script propio: ver
-- config_files/bin_configs/screenshot-path.
local screenshotSave = "screenshot-path"

-- ALT + Print: la ventana enfocada completa, sin seleccionar con el mouse.
local screenshotWindow = "hyprshot -m window -m active --clipboard-only"

-- SUPER + Print: el monitor activo entero.
local screenshotMonitor = "hyprshot -m output -m active --clipboard-only"

-- SUPER + A : abre la referencia de atajos en una terminal flotante.
-- El titulo 'ayuda-atajos' es lo que matchea la window_rule del final del archivo
-- para que salga flotante y no como una ventana mas en el mosaico.
-- Usa glow si esta instalado (renderiza las tablas) y cae a less si no, asi el
-- atajo nunca queda roto.
local ayuda = "foot --title=ayuda-atajos -e sh -c "
    .. "'D=$HOME/config_files/docs/hyprland/README.md; "
    .. 'if command -v glow >/dev/null 2>&1; then glow -p "$D"; else less "$D"; fi\''

---- AUTOSTART ----
-------------------

-- See https://wiki.hypr.land/Configuring/Basics/Autostart/

-- Autostart necessary processes (like notifications daemons, status bars, etc.)
-- Or execute your favorite apps at launch like this:
--
hl.on("hyprland.start", function()
  -- GTK 4 Apps
  hl.exec_cmd('gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"')
  -- GTK 3 Apps
  hl.exec_cmd('gsettings set org.gnome.desktop.interface gtk-theme "adw-gtk3-dark"')

  hl.exec_cmd(terminal)
  -- Fondo de pantalla. La elección al azar entre las imágenes de
  -- config_files/wallpapers la hace hyprpaper.conf con 'order = random'.
  hl.exec_cmd("hyprpaper")
  -- auto-reload.sh LANZA waybar además de vigilarla y recargarla, así que acá no va
  -- un 'hl.exec_cmd("waybar")' aparte: serían dos barras superpuestas, y la que
  -- supervisa el script no sería la visible. Ver el encabezado de auto-reload.sh.
  hl.exec_cmd("~/.config/waybar/auto-reload.sh")
  hl.exec_cmd("hypridle")
  hl.exec_cmd("mako")
  hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
  hl.exec_cmd("wl-paste --watch cliphist store")
end)

-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Environment-variables/

hl.env("XCURSOR_SIZE", settings("CURSOR_SIZE", "24"))
hl.env("HYPRCURSOR_SIZE", settings("CURSOR_SIZE", "24"))
-- Qt Apps (Requires qt5ct/qt6ct)
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "wayland")
hl.env("ELECTRON_ENABLE_WAYLAND", 1)
-----------------------
----- PERMISSIONS -----
-----------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
-- for security reasons

-- hl.config({
--   ecosystem = {
--     enforce_permissions = true,
--   },
-- })

-- hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
-- hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")
-- hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")

-----------------------
---- LOOK AND FEEL ----
-----------------------

-- Refer to https://wiki.hypr.land/Configuring/Basics/Variables/
hl.config({
  general = {
    gaps_in = 2,
    gaps_out = 5,

    border_size = 2,

    col = {
      -- Bordes monocromos sobre la escala Tailwind Zinc del resto del tema (waybar,
      -- rofi, mako). El activo va de zinc-400 a zinc-600: sin color propio, el borde
      -- se lee como profundidad en vez de como decoración, y el acento cyan (#75f1fa)
      -- queda reservado para los componentes que sí comunican estado.
      -- El default de fábrica de Hyprland (33ccff -> 00ff99) se descartó porque ese
      -- verde no aparecía en ninguna otra parte del entorno.
      -- Arranca en zinc-300 y no en zinc-400: con el inactivo en zinc-700, partir de
      -- zinc-400 dejaba sólo dos escalones de diferencia y en las ventanas donde el
      -- degradado llegaba a su extremo oscuro costaba distinguir cuál tenía el foco.
      active_border = { colors = { "rgba(d4d4d8ee)", "rgba(52525bee)" }, angle = 45 },
      -- zinc-700, el mismo gris de los bordes de mako.
      inactive_border = "rgba(3f3f46aa)",
    },

    -- Set to true to enable resizing windows by clicking and dragging on borders and gaps
    resize_on_border = false,

    -- Please see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Tearing/ before you turn this on
    allow_tearing = false,

    layout = "dwindle",
  },

  decoration = {
    -- rounding = 0 para alinear con el default de Omarchy. Con 0, rounding_power
    -- queda inerte (no hay esquina que curvar); se deja por si volvés a subir
    -- rounding. Esto es estetico, no de rendimiento.
    rounding = 0,
    rounding_power = 2,

    -- Change transparency of focused and unfocused windows
    active_opacity = 1.0,
    -- inactive_opacity ANTES estaba en 0.9 (rango válido 0.0-1.0; el 20.0 previo se
    -- truncaba a 1.0 y no tenía efecto). Se subió a 1.0 porque en esta máquina era
    -- la causa principal del lag al cambiar de workspace: el blur de Hyprland se
    -- aplica DETRÁS de las ventanas que tienen transparencia, así que con 0.9 TODAS
    -- las ventanas menos la enfocada eran candidatas a blur y el costo escalaba con
    -- la cantidad de ventanas abiertas. Con 1.0 el costo del blur pasa a ser fijo.
    -- Si querés recuperar el efecto, el precio es ese lag; no hay punto medio barato.
    inactive_opacity = 1.0,

    -- Sombras apagadas: cuestan fill rate en el borde de cada ventana, y en la iGPU
    -- Arc del Ultra 7 165U a 1920x1200@60 con scale 1.5 no hay margen de frame que
    -- regalar. Es la concesión estética más barata de revertir (enabled = true).
    shadow = {
      enabled = settings_bool("SHADOWS_ENABLED", false),
      range = 4,
      render_power = 3,
      color = 0xee1a1a1a,
    },

    -- Blur APAGADO, igual que el default de Omarchy 4 (branch 'quattro').
    --
    -- No costaba nada ya: el blur de Hyprland solo trabaja donde hay algo
    -- TRANSLUCIDO detras de lo cual blurear, y en este escritorio no queda nada
    -- translucido -- inactive_opacity esta en 1.0, foot no define 'alpha' y los
    -- colores de waybar estan todos en alpha 1. Estaba prendido sin efecto.
    -- Se apaga para no dejar una opcion muerta que aparente hacer algo.
    --
    -- Los parametros de abajo quedan inertes con enabled = false; se conservan
    -- para que volver a prenderlo sea cambiar una sola linea. OJO si lo prendes:
    -- vuelve a costar recien cuando algo se vuelva translucido (p.ej. ponerle
    -- 'alpha' a foot), y ahi el costo escala con la cantidad de esas ventanas.
    blur = {
      enabled = settings_bool("BLUR_ENABLED", false),
      size = 2, -- era 3
      passes = 1,
      vibrancy = 0.1696,
      -- xray: blurea el snapshot del fondo en vez del contenido vivo que hay
      -- detrás, o sea que no se recalcula cuando esa ventana de atrás se redibuja.
      new_optimizations = true,
      xray = true,
      popups = false,
    },
  },

  animations = {
    enabled = true,
  },
})

-- Default curves and animations, see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/
hl.curve("easeOutQuint", { type = "bezier", points = { { 0.23, 1 }, { 0.32, 1 } } })
hl.curve("easeInOutCubic", { type = "bezier", points = { { 0.65, 0.05 }, { 0.36, 1 } } })
hl.curve("linear", { type = "bezier", points = { { 0, 0 }, { 1, 1 } } })
hl.curve("almostLinear", { type = "bezier", points = { { 0.5, 0.5 }, { 0.75, 1 } } })
hl.curve("quick", { type = "bezier", points = { { 0.15, 0 }, { 0.1, 1 } } })

-- Default springs
hl.curve("easy", { type = "spring", mass = 1, stiffness = 71.2633, dampening = 15.8273644 })

hl.animation({ leaf = "global", enabled = true, speed = 10, bezier = "default" })
hl.animation({ leaf = "border", enabled = true, speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows", enabled = true, speed = 4.79, spring = "easy" })
hl.animation({ leaf = "windowsIn", enabled = true, speed = 4.1, spring = "easy", style = "popin 87%" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 1.49, bezier = "linear", style = "popin 87%" })
hl.animation({ leaf = "fadeIn", enabled = true, speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut", enabled = true, speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade", enabled = true, speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers", enabled = true, speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn", enabled = true, speed = 4, bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut", enabled = true, speed = 1.5, bezier = "linear", style = "fade" })
hl.animation({ leaf = "fadeLayersIn", enabled = true, speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true, speed = 1.39, bezier = "almostLinear" })
-- Animaciones de workspace APAGADAS, igual que Omarchy 4 (que trae
-- 'hl.animation({ leaf = "workspaces", enabled = false })' en su looknfeel.lua).
--
-- POR QUE: mientras corre la animacion, Hyprland renderiza los DOS workspaces a
-- la vez -- el que sale y el que entra. Cambiando de workspace mas rapido que la
-- animacion nunca se sale de ese estado caro, y encima cada animacion
-- interrumpida se reinicia. Venian en speed 1.94/1.21/1.94 (~190 ms; el 'speed'
-- de Hyprland es la duracion en decimas de segundo), pasaron por 1.0 (~100 ms) y
-- ahora quedan apagadas: el cambio de workspace es instantaneo y no hay frame
-- que presupuestar.
--
-- PARA VOLVER ATRAS: enabled = true, speed = 1.0 en los tres. El fade era lo
-- unico que se pierde; las animaciones de abrir/cerrar ventana siguen intactas.
hl.animation({ leaf = "workspaces", enabled = settings_bool("WORKSPACE_ANIMATIONS", false) })
hl.animation({ leaf = "workspacesIn", enabled = settings_bool("WORKSPACE_ANIMATIONS", false) })
hl.animation({ leaf = "workspacesOut", enabled = settings_bool("WORKSPACE_ANIMATIONS", false) })

-- fadeSwitch (el fade al cambiar el foco entre ventanas) tambien apagado, que es
-- lo otro que Omarchy desactiva explicitamente en su lista de animaciones.
hl.animation({ leaf = "fadeSwitch", enabled = false })
hl.animation({ leaf = "zoomFactor", enabled = true, speed = 7, bezier = "quick" })

-- Ref https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/
-- "Smart gaps" / "No gaps when only"
-- uncomment all if you wish to use that.
-- hl.workspace_rule({ workspace = "w[tv1]", gaps_out = 0, gaps_in = 0 })
-- hl.workspace_rule({ workspace = "f[1]",   gaps_out = 0, gaps_in = 0 })
-- hl.window_rule({
--     name  = "no-gaps-wtv1",
--     match = { float = false, workspace = "w[tv1]" },
--     border_size = 0,
--     rounding    = 0,
-- })
-- hl.window_rule({
--     name  = "no-gaps-f1",
--     match = { float = false, workspace = "f[1]" },
--     border_size = 0,
--     rounding    = 0,
-- })

-- See https://wiki.hypr.land/Configuring/Layouts/Dwindle-Layout/ for more
hl.config({
  dwindle = {
    preserve_split = true, -- You probably want this
  },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Master-Layout/ for more
hl.config({
  master = {
    new_status = "master",
  },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Scrolling-Layout/ for more
hl.config({
  scrolling = {
    fullscreen_on_one_column = true,
  },
})

--------------------
----  XWAYLAND  ----
--------------------

-- force_zero_scaling = true es default de Omarchy. NO es una opcion de
-- rendimiento: hace que las apps X11 se rendericen SIN escalar. Xorg no sabe
-- escalar, asi que en un panel con scale 1.5 como este las apps XWayland salen
-- pixeladas/borrosas; con esto salen NITIDAS, pero mas CHICAS, porque nadie las
-- escala. La compensacion va del lado de X, no de Hyprland: Xft.dpi en
-- ~/.Xresources, o GDK_DPI_SCALE / QT_FONT_DPI segun el toolkit.
--
-- Hoy no cambia nada visible: no hay un solo cliente XWayland corriendo (foot y
-- firefox son Wayland nativo, 'hyprctl clients' los reporta con xwayland: 0).
-- Aplica el dia que abras una app X11. Si te sale demasiado chica y no querés
-- pelear con el DPI de X, poné false y volvés al comportamiento anterior.
hl.config({
  xwayland = {
    force_zero_scaling = true,
  },
})

-----------------
----  DEBUG  ----
-----------------

-- overlay = true dibuja el HUD de frametimes de Hyprland (tiempo de render por
-- monitor). Queda en false: es una herramienta de medición, no algo para tener
-- puesto todo el día. Se usó una vez para verificar los ajustes de blur/sombras/
-- animaciones de este archivo y el lag al cambiar de workspace se fue, así que
-- cumplió su función.
--
-- CUÁNDO VOLVER A PRENDERLO: si el lag reaparece. Poné overlay = true, cambiá de
-- workspace rápido y leé el frametime contra el presupuesto de 16.6 ms (panel de
-- 60 Hz). Cómo interpretarlo:
--
--   > 16 ms  => es el compositor. Queda margen apagando los tres leaves
--              'workspaces*' (enabled = false) y/o blur.enabled = false.
--   < 16 ms  => el compositor NO es el cuello de botella; es más abajo. Ahí van
--              las pruebas de energía, que son de sesión y se revierten al
--              reiniciar (el GT de render idlea en RC6 por debajo de su min_freq,
--              así que una ráfaga corta espera la rampa del GuC):
--
--                powerprofilesctl set performance
--                echo 1200 | sudo tee \
--                  /sys/class/drm/card0/device/tile0/gt0/freq0/min_freq
--
--              Y si tampoco es eso, recién ahí el driver: 'gpumemwatch report' y
--              los TLB invalidation fence timeout de xe (ver etc/cmdline.d).
--
-- Complemento en cualquier caso: 'sudo intel_gpu_top' para ocupación y
-- frecuencia real de la iGPU.
hl.config({
  debug = {
    overlay = false,
  },
})

----------------
----  MISC  ----
----------------

hl.config({
  misc = {
    force_default_wallpaper = -1,  -- Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = false, -- If true disables the random hyprland logo / anime girl background. :(

    -- Redibujar en cada paso intermedio de un resize o de un drag con mouse es
    -- trabajo por frame que no aporta nada: la ventana igual termina donde la
    -- soltás. Apagarlas no cambia el resultado, solo saca frames del camino.
    animate_manual_resizes = settings_bool("ANIMATE_RESIZES", false),
    animate_mouse_windowdragging = settings_bool("ANIMATE_RESIZES", false),
  },
})

---------------
---- INPUT ----
---------------

hl.config({
  input = {
    kb_layout = settings("KB_LAYOUT", "latam,es"),
    --kb_layout    = "es",
    kb_variant = settings("KB_VARIANT", ""),
    kb_model = settings("KB_MODEL", ""),
    kb_options = settings("KB_OPTIONS", "grp:alt_shift_toggle"),
    kb_rules = "",

    follow_mouse = 1,

    sensitivity = settings_num("MOUSE_SENSITIVITY", 0), -- -1.0 - 1.0, 0 means no modification.

    touchpad = {
      natural_scroll = settings_bool("TOUCHPAD_NATURAL_SCROLL", true),
    },
  },
})

hl.gesture({
  fingers = 3,
  direction = "horizontal",
  action = "workspace",
})

-- Per-device overrides: MOUSE_DEVICE_<n>_<option> in ~/.local_host_settings.
-- Generic plumbing only: no device name/handedness is hardcoded here, so each
-- machine configures its own devices in its local settings file.
-- Supported options: NAME (required), LEFT_HANDED, SENSITIVITY,
-- NATURAL_SCROLL, ACCEL_PROFILE, SCROLL_METHOD, ENABLED.
-- Device name must match `hyprctl devices -j` exactly, or use "address:..." to
-- pin a specific physical unit. See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Devices/
local device_conv = {
  name = "raw", left_handed = "bool", sensitivity = "num",
  natural_scroll = "bool", enabled = "bool",
  accel_profile = "raw", scroll_method = "raw",
}
local device_groups, device_indexes = {}, {}
for key, value in pairs(_cfg) do
  local idx, opt = key:match("^MOUSE_DEVICE_(%d+)_(.+)$")
  if idx and device_conv[opt:lower()] then
    idx = tonumber(idx)
    if not device_groups[idx] then
      device_groups[idx] = {}
      device_indexes[#device_indexes + 1] = idx
    end
    device_groups[idx][opt:lower()] = value
  end
end
table.sort(device_indexes)
for _, idx in ipairs(device_indexes) do
  local group = device_groups[idx]
  local prefix = "MOUSE_DEVICE_" .. idx .. "_"
  if group.name and group.name ~= "" then
    local device = { name = group.name }
    if group.left_handed    then device.left_handed    = settings_bool(prefix .. "LEFT_HANDED", false) end
    if group.sensitivity    then device.sensitivity    = settings_num(prefix .. "SENSITIVITY", 0) end
    if group.natural_scroll then device.natural_scroll = settings_bool(prefix .. "NATURAL_SCROLL", false) end
    if group.accel_profile  then device.accel_profile  = settings(prefix .. "ACCEL_PROFILE") end
    if group.scroll_method  then device.scroll_method  = settings(prefix .. "SCROLL_METHOD") end
    if group.enabled        then device.enabled        = settings_bool(prefix .. "ENABLED", true) end
    hl.device(device)
  end
end

---------------------
---- KEYBINDINGS ----
---------------------

local mainMod = "SUPER" -- Sets "Windows" key as main modifier
local secondMod = "SUPER + SHIFT"

-- Example binds, see https://wiki.hypr.land/Configuring/Basics/Binds/ for more
local closeWindowBind = hl.bind(secondMod .. " + C", hl.dsp.window.close())
-- closeWindowBind:set_enabled(false)
hl.bind(
  secondMod .. " + M",
  hl.dsp.exec_cmd("command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch 'hl.dsp.exit()'")
)
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())
--hl.bind(mainMod .. " + J", hl.dsp.layout("togglesplit")) -- dwindle only

hl.bind(mainMod .. " + B", hl.dsp.exec_cmd(browser))
hl.bind(mainMod .. " + Return", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + Space", hl.dsp.exec_cmd(launcher))
hl.bind(secondMod .. " + Space", hl.dsp.exec_cmd(runner))

-- Move focus with mainMod + arrow keys
hl.bind(mainMod .. " + H", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + L", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + K", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + J", hl.dsp.focus({ direction = "down" }))

hl.bind(secondMod .. " + H", hl.dsp.window.move({ direction = "left" }))
hl.bind(secondMod .. " + L", hl.dsp.window.move({ direction = "right" }))
hl.bind(secondMod .. " + K", hl.dsp.window.move({ direction = "up" }))
hl.bind(secondMod .. " + J", hl.dsp.window.move({ direction = "down" }))

hl.bind(secondMod .. " + T", hl.dsp.window.float({ action = "toggle" }))
-- Los dos modos de agrandar una ventana, juntos a proposito para que se lean de a pares.
-- 'maximized' la estira hasta los bordes del monitor pero respeta la waybar, los gaps y
-- la barra de titulo; 'fullscreen' se come la pantalla entera, sin nada alrededor. Son
-- los dos unicos valores que acepta el dispatcher (el propio binario lo dice si te
-- equivocas: 'expected fullscreen/maximized').
--
-- Se escribe "CONTROL" a mano en vez de usar thirdMod porque esa variable recien se
-- define mas abajo, con los binds de workspaces; la combinacion resultante es la misma.
hl.bind(secondMod .. " + F", hl.dsp.window.fullscreen({ mode = "maximized" }))
hl.bind(mainMod .. " + CONTROL + F", hl.dsp.window.fullscreen({ mode = "fullscreen" }))

hl.bind(secondMod .. " + Q", hl.dsp.exec_cmd("hyprlock"))

-- SALIDA DE EMERGENCIA para una pantalla que quedo negra. 'D' de DPMS.
-- Un 'dpms off' que NO haya disparado hypridle queda PEGADO: el 'on-resume' de
-- hypridle solo corre para el listener que efectivamente hizo timeout, asi que si
-- el apagado vino de otro lado (un hyprctl a mano, una prueba, un script) mover el
-- mouse no enciende nada y la unica salida era reiniciar el equipo. Este bind se
-- puede pulsar A CIEGAS con la pantalla apagada: el teclado le sigue llegando a
-- Hyprland aunque no haya senal de video.
-- OJO: el campo es 'action', NO 'state'. Con una clave desconocida el dispatcher cae
-- a TOGGLE (es el valor 0 del enum), o sea que dpms({ state = "on" }) APAGARIA una
-- pantalla encendida. Ver la explicacion larga en hypridle.conf.
hl.bind(mainMod .. " + D", hl.dsp.dpms({ action = "on" }))

-- Historial del portapapeles (cliphist): elegir una entrada con rofi y copiarla
hl.bind(
  secondMod .. " + V",
  hl.dsp.exec_cmd("cliphist list | rofi -dmenu -p 'Portapapeles' | cliphist decode | wl-copy")
)

-- Selector de ventanas del workspace ACTUAL. Va a un script (bin_configs/pick-window)
-- y no a un 'rofi -show window' porque ese modo lista las ventanas de todos los
-- workspaces; el que filtraba por escritorio actual ('windowcd') no existe en el rofi
-- de Wayland. El script le pide la lista a Hyprland y usa rofi sólo como menú.
-- W de 'window'. La idea original era SUPER + ALT, pero no es viable: ALT es un
-- MODIFICADOR, y al pulsarlo Hyprland actualiza el estado de modificadores en vez de
-- mandarlo por el matcher de binds. Probado que no dispara ni como bind normal ni con
-- release = true (el 'bindr' de Hyprland, que engancha el soltar y es lo que suele
-- rescatar estos casos). Con una tecla normal funciona a la primera.
hl.bind(mainMod .. " + W", hl.dsp.exec_cmd("pick-window"))

-- Variante que lista TODOS los workspaces. Elegir una ventana de otro workspace salta
-- a ese workspace, restaura lo que estuviera maximizado y la enfoca: las tres cosas
-- las hace el dispatcher de foco de Hyprland solo, el script no las programa.
hl.bind(secondMod .. " + W", hl.dsp.exec_cmd("pick-window --all"))

-- Buscar un archivo en cualquier lugar de ~ y abrirlo con su aplicación por defecto.
-- F de 'find' / 'file', y queda al lado del Ctrl+F de zsh, que hace lo mismo dentro de
-- la terminal. SUPER + F estaba libre; SUPER + SHIFT + F (pantalla completa) no se toca.
--
-- El script (bin_configs/find-file) elige frontend solo: desde acá no hay terminal, así
-- que saca el menú de rofi; corrido a mano en una terminal saca fzf con preview.
--
-- The rofi face also looks at the clipboard: if you have a path or a URL copied, it
-- offers it at the top and preselected (Enter without typing anything opens it; Alt+1
-- opens it even with a filter). Details in docs/hyprland/README.md. The fzf face does
-- not do that.
hl.bind(mainMod .. " + F", hl.dsp.exec_cmd("find-file"))

-- Recent files: downloads, screenshots, recently opened (xbel) and recently modified,
-- in one rofi menu with actions to open, copy the path, open the folder, open a terminal
-- there or move to the trash. 'O' because 'R' (recent) is taken by the resize submap.
-- Script: bin_configs/recent-files; details in docs/hyprland/README.md.
hl.bind(mainMod .. " + O", hl.dsp.exec_cmd("recent-files"))

-- Dictado por voz (voxtype). 'T' de 'transcribir'.
-- Toggle: una pulsación arranca a grabar, otra para y transcribe.
-- Da por hecho que el demonio corre y que el bind del compositor es la única
-- vía de activación (ver config.toml: [hotkey] enabled = false, state_file = "auto").
hl.bind(mainMod .. " + T", hl.dsp.exec_cmd("voxtype record toggle"))

-- Activar el submapa al pulsar Mod + R
hl.bind("SUPER + R", hl.dsp.submap("resize"))
-- Definición del submapa "resize"
hl.define_submap("resize", function()
  -- Ajustar tamaño de ventana activa (manteniendo presionado con repeating = true)
  hl.bind("L", hl.dsp.window.resize({ x = 10, y = 0, relative = true }), { repeating = true })
  hl.bind("H", hl.dsp.window.resize({ x = -10, y = 0, relative = true }), { repeating = true })
  hl.bind("K", hl.dsp.window.resize({ x = 0, y = -10, relative = true }), { repeating = true })
  hl.bind("J", hl.dsp.window.resize({ x = 0, y = 10, relative = true }), { repeating = true })

  -- Salir del submapa al presionar Enter o Escape
  hl.bind("Return", hl.dsp.submap("reset"))
  hl.bind("escape", hl.dsp.submap("reset"))
end)

-- Mover el WORKSPACE ACTIVO de una pantalla a otra. 'M' de monitor: SUPER + M
-- estaba libre (SUPER + SHIFT + M es apagar, esa no se toca).
--
-- Va en un submapa y no en un acorde por dos razones. La primera es que las
-- combinaciones direccionales ya estan las tres tomadas: SUPER mueve el foco,
-- SUPER + SHIFT mueve la ventana dentro del tiling y SUPER + CONTROL cambia de
-- workspace; lo que quedaba libre era SUPER + CONTROL + SHIFT, tres
-- modificadores para algo que se usa poco. La segunda es que el caso real no
-- es mover UN workspace: es enchufar el monitor y reacomodar dos o tres
-- seguidos. En el submapa se entra una vez y se sale con Esc.
--
-- Waybar ya muestra el submapa activo (modulo hyprland/submap), asi que no
-- hace falta ninguna notificacion extra para saber que uno esta adentro.
hl.bind(mainMod .. " + M", hl.dsp.submap("monitor"))

hl.define_submap("monitor", function()
  -- Las direcciones son las mismas que en el resto de la config: H/L para
  -- izquierda/derecha, K/J para arriba/abajo. Las flechas hacen exactamente lo
  -- mismo, por si en el momento salen antes que las letras.
  --
  -- El monitor se elige por DIRECCION (l/r/u/d) y no por indice relativo
  -- (+1/-1) porque el indice da la vuelta: en dos pantallas, empujar a la
  -- derecha desde la de la derecha te devolveria a la izquierda. Con la
  -- direccion no pasa nada y Hyprland avisa "Monitor not found", que es lo que
  -- uno espera al empujar contra el borde.
  --
  -- Sin 'workspace' en la tabla, el dispatcher usa el workspace activo.
  hl.bind("H", hl.dsp.workspace.move({ monitor = "l" }))
  hl.bind("L", hl.dsp.workspace.move({ monitor = "r" }))
  hl.bind("K", hl.dsp.workspace.move({ monitor = "u" }))
  hl.bind("J", hl.dsp.workspace.move({ monitor = "d" }))

  hl.bind("Left", hl.dsp.workspace.move({ monitor = "l" }))
  hl.bind("Right", hl.dsp.workspace.move({ monitor = "r" }))
  hl.bind("Up", hl.dsp.workspace.move({ monitor = "u" }))
  hl.bind("Down", hl.dsp.workspace.move({ monitor = "d" }))

  -- Salir del submapa al presionar Enter o Escape.
  --
  -- Al salir se renumeran los workspaces (bin_configs/sort-workspaces): mover uno de
  -- pantalla NO le cambia el numero, asi que despues de reacomodar dos o tres quedan
  -- intercalados (izquierda 1,3,5 / derecha 2,4,6) y eso se ve en la barra y se camina
  -- con la navegacion relativa. Salir del submapa es exactamente el momento en que
  -- terminaste de acomodar, asi que es donde corresponde ordenar.
  --
  -- El separador es ';' y no '&&' a proposito: si sort-workspaces no esta instalado --
  -- vive en bin_configs y necesita link-bins.sh -- igual tenes que poder salir del
  -- submapa.
  local salir = [[sort-workspaces; hyprctl dispatch 'hl.dsp.submap("reset")']]
  hl.bind("Return", hl.dsp.exec_cmd(salir))
  hl.bind("escape", hl.dsp.exec_cmd(salir))
end)

-- Switch workspaces with mainMod + [0-9]
-- Move active window to a workspace with mainMod + SHIFT + [0-9]
for i = 1, 10 do
  local key = i % 10 -- 10 maps to key 0
  hl.bind(mainMod .. " + " .. key, hl.dsp.focus({ workspace = i }))
  hl.bind(secondMod .. " + " .. key, hl.dsp.window.move({ workspace = i }))
end

-- Example special workspace (scratchpad)
hl.bind(mainMod .. " + S", hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))

-- Scroll through existing workspaces with mainMod + scroll.
--
-- "e+-1" recorre TODOS los workspaces que existan, ordenados por ID y sin mirar en que
-- monitor estan: un solo recorrido 1..N que cruza a la otra pantalla al llegar al final
-- de la primera.
--
-- Eso funciona porque los numeros estan ordenados. Si quedaran intercalados -- izquierda
-- 1,3,5 y derecha 2,4 -- avanzar desde el 1 te mandaria a la otra pantalla y volveria,
-- que es justo lo que se siente roto. De que no queden intercalados se encarga
-- sort-workspaces al salir del modo monitor (bin_configs/sort-workspaces).
--
-- La alternativa es "m+-1", que se queda en los workspaces de la pantalla actual y da la
-- vuelta ahi mismo sin pasar nunca a la otra. Se probo y no es lo que se quiere: obliga a
-- cambiar de pantalla aparte, con el foco direccional.
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Capturas de pantalla. Van en la tecla Print porque SUPER+S ya está tomado por el scratchpad "magic".
-- Los comandos están definidos arriba, en el bloque MY PROGRAMS.
hl.bind("Print", hl.dsp.exec_cmd(screenshot))                      -- región + anotar + portapapeles
hl.bind("SHIFT + Print", hl.dsp.exec_cmd(screenshotCopy))          -- región -> portapapeles
hl.bind("CONTROL + Print", hl.dsp.exec_cmd(screenshotSave))        -- región -> ~/Pictures + portapapeles
hl.bind("ALT + Print", hl.dsp.exec_cmd(screenshotWindow))          -- ventana activa -> portapapeles
hl.bind(mainMod .. " + Print", hl.dsp.exec_cmd(screenshotMonitor)) -- monitor completo -> portapapeles

-- Ayuda: referencia de atajos. 'A' de ayuda.
-- Se usa una LETRA a proposito: el layout de este equipo es latam, donde la barra
-- '/' no tiene tecla propia (se escribe con Shift+7), asi que un bind sobre el
-- keysym 'slash' no se dispara con la combinacion que uno esperaria. Las letras
-- estan en la misma posicion fisica en cualquier layout.
hl.bind(mainMod .. " + A", hl.dsp.exec_cmd(ayuda))

-- Monitor Setup: perfil de monitores externos por EDID en una terminal flotante
-- (bin_configs/monitor-setup). 'F2' esta en la primer fila de teclas de funcion,
-- libre en este esquema; SUPER + F ya es find-file y se elige un F2 a proposito
-- para que el launcher de aplicaciones no lo pise.
-- '-W 110x28' fuerza el tamaño en columnas/filas para que la statusbar (96 cols
-- de atajos) entre completa; el window rule flotante lo acomoda al monitor.
-- La fuente va en size=10 (vs 12 del foot.ini) para que el flotante se lea bien.
local monitorSetup =
    "foot --title=monitor-setup '--font=JetBrainsMono Nerd Font:size=10' -W 110x28 -e monitor-setup"
hl.bind(mainMod .. " + F2", hl.dsp.exec_cmd(monitorSetup))

-- Tu nueva combinación base: SUPER + CONTROL
local thirdMod = mainMod .. " + CONTROL"

-- ==========================================
-- 1. CAMBIAR DE WORKSPACE (Navegación)
-- ==========================================

-- El recorrido es "e+-1" (ver el comentario del scroll, mas arriba): un solo 1..N que
-- atraviesa las dos pantallas, apoyado en que sort-workspaces mantiene los numeros en
-- orden visual.

-- Moverse al espacio de trabajo ANTERIOR con 'H' (Izquierda)
hl.bind(thirdMod .. " + H", hl.dsp.focus({ workspace = "e-1" }))

-- Moverse al espacio de trabajo SIGUIENTE con 'L' (Derecha)
hl.bind(thirdMod .. " + L", hl.dsp.focus({ workspace = "e+1" }))

-- Opcionales (Vertical)
hl.bind(thirdMod .. " + K", hl.dsp.focus({ workspace = "e-1" })) -- Arriba / Anterior
hl.bind(thirdMod .. " + J", hl.dsp.focus({ workspace = "e+1" })) -- Abajo / Siguiente

-- Renumerar los workspaces a mano, sin pasar por el submapa SUPER + M: quedan 1..N en
-- orden visual, la pantalla de la izquierda primero. 'M' de monitor, con el modificador
-- de la navegacion entre workspaces, que es de lo que se trata.
hl.bind(thirdMod .. " + M", hl.dsp.exec_cmd("sort-workspaces"))

-- ==========================================
-- 2. REORDENAR WORKSPACES (arrastrar de posicion)
-- ==========================================

-- Arrastra el workspace ACTIVO una posicion, empujando a los demas para que la secuencia
-- siga siendo 1..N sin huecos. Parado en el 1 de "1,2,3,4", dos veces a la derecha deja
-- al que era 1 como 3, al 2 como 1 y al 3 como 2. Seguis en el mismo workspace y con las
-- mismas ventanas: lo unico que cambia es su numero, o sea su lugar en la barra y en la
-- navegacion relativa.
--
-- Las mismas teclas que la navegacion de arriba, mas SHIFT. Es la convencion que ya usa
-- el resto de la config: SUPER + n ENFOCA el workspace n y SUPER + SHIFT + n MUEVE la
-- ventana ahi. Aca, thirdMod + H/L ENFOCA el workspace vecino y agregarle SHIFT MUEVE el
-- workspace hacia ese lado.
--
-- SIN 'repeating'. Con auto-repeticion, mantener la tecla apretada disparaba el script
-- decenas de veces por segundo y el workspace volaba 10 o 20 posiciones de un saque, que
-- para reordenar es puro sobretiro: uno quiere dejarlo en un lugar concreto. Una
-- pulsacion, una posicion. Si alguna vez se prefiere lo otro, agregarle
-- '{ repeating = true }' es seguro: el script se protege solo con un flock que descarta
-- las invocaciones encimadas (dos renumerados entrelazados se pisan los IDs entre si).
--
-- Ojo si alguna vez se vuelve el modulo de waybar a 'hyprland/workspaces': ahi cada
-- movimiento tiene que mandarle un SIGUSR2 a la barra, y con auto-repeticion esa rafaga
-- de recargas la mata con SIGSEGV (medido: 25 senales en 2 segundos alcanzan). Con
-- 'ext/workspaces', que es lo que hay ahora, no se manda ninguna senal y el problema no
-- existe.
--
-- NO cruza de pantalla a proposito: esto renumera, y mandar un workspace a la otra
-- pantalla es 'moveworkspacetomonitor', que es lo que hace el submapa SUPER + M. Los dos
-- se llevan bien -- reordenar dentro de una pantalla deja un resultado que
-- sort-workspaces no toca --, asi que se pueden usar en cualquier orden.
--
-- El script vive en bin_configs/, o sea que en una maquina ya instalada hay que correr
-- 'bash ~/config_files/scripts/link-bins.sh' para crearle el symlink: no viaja solo con
-- el git pull. Si falta, el atajo no hace nada.
hl.bind(thirdMod .. " + SHIFT + H", hl.dsp.exec_cmd("move-workspace left"))
hl.bind(thirdMod .. " + SHIFT + L", hl.dsp.exec_cmd("move-workspace right"))

-- Los verticales, por simetria con la navegacion (que tiene K/J ademas de H/L).
hl.bind(thirdMod .. " + SHIFT + K", hl.dsp.exec_cmd("move-workspace left"))
hl.bind(thirdMod .. " + SHIFT + J", hl.dsp.exec_cmd("move-workspace right"))

-- Laptop multimedia keys for volume and LCD brightness
hl.bind(
  "XF86AudioRaiseVolume",
  hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"),
  { locked = true, repeating = true }
)
hl.bind(
  "XF86AudioLowerVolume",
  hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),
  { locked = true, repeating = true }
)
hl.bind(
  "XF86AudioMute",
  hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),
  { locked = true, repeating = true }
)
hl.bind(
  "XF86AudioMicMute",
  hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),
  { locked = true, repeating = true }
)
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"), { locked = true, repeating = true })

-- Requires playerctl
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- See https://wiki.hypr.land/Configuring/Basics/Window-Rules/
-- and https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/

-- Example window rules that are useful

local suppressMaximizeRule = hl.window_rule({
  -- Ignore maximize requests from all apps. You'll probably like this.
  name = "suppress-maximize-events",
  match = { class = ".*" },

  suppress_event = "maximize",
})
-- suppressMaximizeRule:set_enabled(false)

hl.window_rule({
  -- Fix some dragging issues with XWayland
  name = "fix-xwayland-drags",
  match = {
    class = "^$",
    title = "^$",
    xwayland = true,
    float = true,
    fullscreen = false,
    pin = false,
  },

  no_focus = true,
})

-- Layer rules also return a handle.
-- local overlayLayerRule = hl.layer_rule({
--     name  = "no-anim-overlay",
--     match = { namespace = "^my-overlay$" },
--     no_anim = true,
-- })
-- overlayLayerRule:set_enabled(false)

-- Hyprland-run windowrule
hl.window_rule({
  name = "move-hyprland-run",
  match = { class = "hyprland-run" },

  move = "20 monitor_h-120",
  float = true,
})

-- La ventana de ayuda (SUPER + A) sale flotante en vez de sumarse al mosaico.
-- Con 'size' y 'center' para que abra amplia y centrada: la referencia usa
-- glow y necesita ancho para no renglonear el texto a lo loco.
hl.window_rule({
  name = "ayuda-flotante",
  match = { title = "^ayuda-atajos$" },

  float = true,
  center = true,
  size = "(monitor_w*0.65) (monitor_h*0.7)",
})

-- Monitor Setup (SUPER + F2) sale flotante centrada igual que la ayuda: la TUI
-- muestra conectar/perfiles/draft y necesita pantalla real para que se lea de un
-- vistazo, sin reacomodar el mosaico por la consulta. El match va por titulo
-- ('monitor-setup', el --title= que le pasa el bind de arriba).
--
-- 'stay_focused' porque la ventana flotante pierde el foco apenas el mouse sale
-- de ella y la TUI se queda dibujada sin escuchar teclas: q/Esc no la cierran.
-- Mismo arreglo que los popups de Zoom (ver regla zoom-menu-stay-focused abajo).
--
-- NO hay regla de 'size' a proposito: el tamaño lo define foot con '-W 110x28'
-- (celdas), que es lo unico que calza exacto con la TUI (la statusbar de ~100
-- cols entra completa). Si Hyprland ademas forzara un size en píxeles logicos,
-- las dos metricas no coinciden y quedan margenes negros asimetricos alrededor.
hl.window_rule({
  name = "monitor-setup-flotante",
  match = { title = "^monitor-setup$" },

  float = true,
  center = true,
  stay_focused = true,
})

-- Las TUI que abren los clics de Waybar (volumen, bluetooth, red, CPU, memoria) son
-- consultas puntuales que se cierran enseguida: salen flotantes para no reacomodar el
-- mosaico entero por una mirada de dos segundos.
--
-- El match va por TITULO y no por clase porque todas son la misma app (ghostty); lo
-- que las distingue es el '--title=' que les pasa cada on-click en waybar/config.jsonc.
-- Verificado que ese título sobrevive a la TUI: htop no lo pisa.
--
-- Sin 'center' ni 'size' a propósito: se deja que Hyprland las ubique y que cada una
-- conserve el tamaño que pide.
hl.window_rule({
  name = "waybar-tui-flotantes",
  match = { title = "^(wiremix|bluetui|nmtui|htop|rclone-sync|rclone-log)$" },

  float = true,
})

-- btop va aparte porque necesita mucho más espacio que las otras: con el tamaño por
-- defecto de ghostty (800x600) se queja de que la terminal es chica y no dibuja sus
-- paneles.
--
-- OJO con el formato: 'size' sólo acepta una TABLA DE DOS NÚMEROS en píxeles lógicos.
-- Las variantes size = "80% 85%" y size = { "80%", "85%" } se aceptan sin error pero
-- NO hacen nada -- la ventana sale con el tamaño por defecto y uno no se entera.
-- Verificado probando las tres formas.
--
-- Píxeles lógicos (y no físicos) significa que el recuento de caracteres se mantiene
-- entre monitores con distinta escala, que es lo que le importa a btop.
hl.window_rule({
  name = "btop-flotante-grande",
  match = { title = "^btop$" },

  float = true,
  size = { 1024, 680 },
})

-- ram-top (el clic en el modulo de memoria de la barra) va aparte por el mismo motivo
-- que btop: necesita ancho. Su segunda vista pone el desglose del proceso en un panel
-- al costado, y ese panel solo entra si le quedan unas 52 columnas; por debajo de eso
-- fzf lo manda abajo, que funciona pero se ve mas apretado. Con este tamano entra al
-- costado, que es como se lee mejor.
--
-- Vale la misma advertencia de arriba: 'size' solo acepta una tabla de dos numeros en
-- pixeles logicos. Las variantes con porcentajes se aceptan sin error y no hacen nada.
hl.window_rule({
  name = "ram-top-flotante",
  match = { title = "^ram-top$" },

  float = true,
  size = { 1200, 720 },
})

-- Zoom popup windows disappear on Hyprland due to focus behavior: the popup
-- opens as a floating window, Hyprland removes focus when the mouse moves off it,
-- and Zoom closes the popup on focus loss. stay_focused keeps the popup focused
-- while visible so the exit/confirm buttons stay clickable.
-- See https://github.com/hyprwm/Hyprland/issues/4809
hl.window_rule({
  name = "zoom-menu-stay-focused",
  match = { class = "^zoom$", title = "^menu window$" },

  stay_focused = true,
})

hl.window_rule({
  name = "zoom-confirm-stay-focused",
  match = { class = "^zoom$", title = "^confirm window$" },

  stay_focused = true,
})

-- Zoom a veces minimiza a la bandeja en vez de salir: la ventana desaparece pero el
-- proceso sigue corriendo, y como Zoom es de instancia unica no se vuelve a abrir hasta
-- matarlo. Este atajo lo mata entero (la ventana + los procesos auxiliares como el de
-- compartir pantalla). Z de Zoom.
hl.bind("SUPER + CONTROL + Z", hl.dsp.exec_cmd("pkill -f '/usr/bin/zoom' || true"))
