-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --


-- This is an example Hyprland Lua config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can (and should!!) split this configuration into multiple files
-- Create your files separately and then require them like this:
-- require("myColors")


------------------
---- MONITORS ----
------------------

-- See https://wiki.hypr.land/Configuring/Basics/Monitors/
hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = "auto",
  },
  {
    output = "DP-1",
    mode = "2560x1080@60",
    position = "auto-right",
    scale = "auto",
  }
-- {
--   output = "HDMI-A-1",
--   mode = "3840x2160@60",
--   position = "auto-right",
--   scale = "auto",
-- }
)


---------------------
---- MY PROGRAMS ----
---------------------

-- Set programs that you use
local terminal          = "ghostty"
local fileManager       = "thunar"
local launcher          = "rofi -show drun -show-icons"
local runner            = "rofi -show run"
local bar               = "waybar"
local browser           = "firefox"

-- Capturas de pantalla (los binds están más abajo, junto a la tecla Print).
--
-- Notas comunes a todos:
--   -z / --freeze     congela la imagen al iniciar la selección. Sin esto no se
--                     pueden capturar menús desplegados ni tooltips: desaparecen
--                     apenas movés el mouse para seleccionar.
--   --clipboard-only  hyprshot por defecto guarda en disco Y copia; esta opción
--                     evita llenar ~/Pictures con capturas descartables.
--   -m active         requiere repetir --mode con la selección buscada
--                     (window o output), es la sintaxis que pide hyprshot.

-- Print: región, anotar en satty, y al portapapeles.
--   --copy-command wl-copy   satty NO sabe copiar en Wayland por su cuenta; sin
--                            esta opción el botón de copiar no hace nada.
--   --actions-on-enter ...   Enter copia, sin tener que buscar el botón.
--   --early-exit copy        cierra satty apenas copió, en vez de quedar abierto.
local screenshot        = "hyprshot -m region -z --raw | satty --filename - "
    .. "--copy-command wl-copy --actions-on-enter save-to-clipboard --early-exit copy"

-- SHIFT + Print: región directo al portapapeles, sin pasar por satty.
local screenshotCopy    = "hyprshot -m region -z --clipboard-only"

-- CONTROL + Print: región a ~/Pictures/screenshots y además al portapapeles.
-- El propio hyprshot hace mkdir -p del directorio, así que no hace falta crearlo.
local screenshotSave    = "hyprshot -m region -z -o $HOME/Pictures/screenshots"

-- ALT + Print: la ventana enfocada completa, sin seleccionar con el mouse.
local screenshotWindow  = "hyprshot -m window -m active --clipboard-only"

-- SUPER + Print: el monitor activo entero.
local screenshotMonitor = "hyprshot -m output -m active --clipboard-only"

-- SUPER + A : abre la referencia de atajos en una terminal flotante.
-- El titulo 'ayuda-atajos' es lo que matchea la window_rule del final del archivo
-- para que salga flotante y no como una ventana mas en el mosaico.
-- Usa glow si esta instalado (renderiza las tablas) y cae a less si no, asi el
-- atajo nunca queda roto.
local ayuda             = "ghostty --title=ayuda-atajos -e sh -c "
    .. "'D=$HOME/config_files/docs/hyprland/README.md; "
    .. "if command -v glow >/dev/null 2>&1; then glow -p \"$D\"; else less \"$D\"; fi'"


-------------------
---- AUTOSTART ----
-------------------

-- See https://wiki.hypr.land/Configuring/Basics/Autostart/

-- Autostart necessary processes (like notifications daemons, status bars, etc.)
-- Or execute your favorite apps at launch like this:
--
hl.on("hyprland.start", function()
  -- GTK 4 Apps
  hl.exec_cmd('gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"')
  -- GTK 3 Apps
  hl.exec_cmd('gsettings set org.gnome.desktop.interface gtk-theme "adw-gtk3-dark"')

  hl.exec_cmd(terminal)
  -- Fondo de pantalla. La elección al azar entre las imágenes de
  -- config_files/wallpapers la hace hyprpaper.conf con 'order = random'.
  hl.exec_cmd("hyprpaper")
  -- auto-reload.sh LANZA waybar además de vigilarla y recargarla, así que acá no va
  -- un 'hl.exec_cmd("waybar")' aparte: serían dos barras superpuestas, y la que
  -- supervisa el script no sería la visible. Ver el encabezado de auto-reload.sh.
  hl.exec_cmd("~/.config/waybar/auto-reload.sh")
  hl.exec_cmd("hypridle")
  hl.exec_cmd("mako")
  hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
  hl.exec_cmd("wl-paste --watch cliphist store")
end)



-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Environment-variables/

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
-- Qt Apps (Requires qt5ct/qt6ct)
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "wayland")
hl.env("ELECTRON_ENABLE_WAYLAND", 1)
-----------------------
----- PERMISSIONS -----
-----------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
-- for security reasons

-- hl.config({
--   ecosystem = {
--     enforce_permissions = true,
--   },
-- })

-- hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
-- hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")
-- hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")


-----------------------
---- LOOK AND FEEL ----
-----------------------

-- Refer to https://wiki.hypr.land/Configuring/Basics/Variables/
hl.config({
  general = {
    gaps_in          = 2,
    gaps_out         = 5,

    border_size      = 2,

    col              = {
      -- Bordes monocromos sobre la escala Tailwind Zinc del resto del tema (waybar,
      -- rofi, mako). El activo va de zinc-400 a zinc-600: sin color propio, el borde
      -- se lee como profundidad en vez de como decoración, y el acento cyan (#75f1fa)
      -- queda reservado para los componentes que sí comunican estado.
      -- El default de fábrica de Hyprland (33ccff -> 00ff99) se descartó porque ese
      -- verde no aparecía en ninguna otra parte del entorno.
      -- Arranca en zinc-300 y no en zinc-400: con el inactivo en zinc-700, partir de
      -- zinc-400 dejaba sólo dos escalones de diferencia y en las ventanas donde el
      -- degradado llegaba a su extremo oscuro costaba distinguir cuál tenía el foco.
      active_border   = { colors = { "rgba(d4d4d8ee)", "rgba(52525bee)" }, angle = 45 },
      -- zinc-700, el mismo gris de los bordes de mako.
      inactive_border = "rgba(3f3f46aa)",
    },

    -- Set to true to enable resizing windows by clicking and dragging on borders and gaps
    resize_on_border = false,

    -- Please see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Tearing/ before you turn this on
    allow_tearing    = false,

    layout           = "dwindle",
  },

  decoration = {
    rounding         = 2,
    rounding_power   = 2,

    -- Change transparency of focused and unfocused windows
    active_opacity   = 1.0,
    inactive_opacity = 0.9, -- rango válido 0.0-1.0 (el 20.0 anterior se truncaba a 1.0 y no tenía efecto)

    shadow           = {
      enabled      = true,
      range        = 4,
      render_power = 3,
      color        = 0xee1a1a1a,
    },

    blur             = {
      enabled  = true,
      size     = 3,
      passes   = 1,
      vibrancy = 0.1696,
    },
  },

  animations = {
    enabled = true,
  },
})

-- Default curves and animations, see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/
hl.curve("easeOutQuint", { type = "bezier", points = { { 0.23, 1 }, { 0.32, 1 } } })
hl.curve("easeInOutCubic", { type = "bezier", points = { { 0.65, 0.05 }, { 0.36, 1 } } })
hl.curve("linear", { type = "bezier", points = { { 0, 0 }, { 1, 1 } } })
hl.curve("almostLinear", { type = "bezier", points = { { 0.5, 0.5 }, { 0.75, 1 } } })
hl.curve("quick", { type = "bezier", points = { { 0.15, 0 }, { 0.1, 1 } } })

-- Default springs
hl.curve("easy", { type = "spring", mass = 1, stiffness = 71.2633, dampening = 15.8273644 })

hl.animation({ leaf = "global", enabled = true, speed = 10, bezier = "default" })
hl.animation({ leaf = "border", enabled = true, speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows", enabled = true, speed = 4.79, spring = "easy" })
hl.animation({ leaf = "windowsIn", enabled = true, speed = 4.1, spring = "easy", style = "popin 87%" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 1.49, bezier = "linear", style = "popin 87%" })
hl.animation({ leaf = "fadeIn", enabled = true, speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut", enabled = true, speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade", enabled = true, speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers", enabled = true, speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn", enabled = true, speed = 4, bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut", enabled = true, speed = 1.5, bezier = "linear", style = "fade" })
hl.animation({ leaf = "fadeLayersIn", enabled = true, speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true, speed = 1.39, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesIn", enabled = true, speed = 1.21, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesOut", enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "zoomFactor", enabled = true, speed = 7, bezier = "quick" })

-- Ref https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/
-- "Smart gaps" / "No gaps when only"
-- uncomment all if you wish to use that.
-- hl.workspace_rule({ workspace = "w[tv1]", gaps_out = 0, gaps_in = 0 })
-- hl.workspace_rule({ workspace = "f[1]",   gaps_out = 0, gaps_in = 0 })
-- hl.window_rule({
--     name  = "no-gaps-wtv1",
--     match = { float = false, workspace = "w[tv1]" },
--     border_size = 0,
--     rounding    = 0,
-- })
-- hl.window_rule({
--     name  = "no-gaps-f1",
--     match = { float = false, workspace = "f[1]" },
--     border_size = 0,
--     rounding    = 0,
-- })

-- See https://wiki.hypr.land/Configuring/Layouts/Dwindle-Layout/ for more
hl.config({
  dwindle = {
    preserve_split = true, -- You probably want this
  },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Master-Layout/ for more
hl.config({
  master = {
    new_status = "master",
  },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Scrolling-Layout/ for more
hl.config({
  scrolling = {
    fullscreen_on_one_column = true,
  },
})

----------------
----  MISC  ----
----------------

hl.config({
  misc = {
    force_default_wallpaper = -1,    -- Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo   = false, -- If true disables the random hyprland logo / anime girl background. :(
  },
})


---------------
---- INPUT ----
---------------

hl.config({
  input = {
    kb_layout    = "latam,es",
    --kb_layout    = "es",
    kb_variant   = "",
    kb_model     = "",
    kb_options   = "grp:alt_shift_toggle",
    kb_rules     = "",

    left_handed  = true,
    follow_mouse = 1,

    sensitivity  = 0, -- -1.0 - 1.0, 0 means no modification.

    touchpad     = {
      natural_scroll = true,
    },
  },
})

hl.gesture({
  fingers = 3,
  direction = "horizontal",
  action = "workspace"
})

-- Example per-device config
-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Devices/ for more
hl.device({
  name        = "epic-mouse-v1",
  sensitivity = -0.5,
})


---------------------
---- KEYBINDINGS ----
---------------------

local mainMod = "SUPER" -- Sets "Windows" key as main modifier
local secondMod = "SUPER + SHIFT"

-- Example binds, see https://wiki.hypr.land/Configuring/Basics/Binds/ for more
local closeWindowBind = hl.bind(secondMod .. " + C", hl.dsp.window.close())
-- closeWindowBind:set_enabled(false)
hl.bind(secondMod .. " + M",
  hl.dsp.exec_cmd("command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch 'hl.dsp.exit()'"))
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())
--hl.bind(mainMod .. " + J", hl.dsp.layout("togglesplit")) -- dwindle only

hl.bind(mainMod .. " + B", hl.dsp.exec_cmd(browser))
hl.bind(mainMod .. " + T", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + Space", hl.dsp.exec_cmd(launcher))
hl.bind(secondMod .. " + Space", hl.dsp.exec_cmd(runner))

-- Move focus with mainMod + arrow keys
hl.bind(mainMod .. " + H", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + L", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + I", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + K", hl.dsp.focus({ direction = "down" }))

hl.bind(secondMod .. " + H", hl.dsp.window.move({ direction = "left" }))
hl.bind(secondMod .. " + L", hl.dsp.window.move({ direction = "right" }))
hl.bind(secondMod .. " + I", hl.dsp.window.move({ direction = "up" }))
hl.bind(secondMod .. " + K", hl.dsp.window.move({ direction = "down" }))


hl.bind(secondMod .. " + T", hl.dsp.window.float({ action = "toggle" }))
hl.bind(secondMod .. " + F", hl.dsp.window.fullscreen({ mode = "maximized" }))

hl.bind(secondMod .. " + Q", hl.dsp.exec_cmd("hyprlock"))

-- SALIDA DE EMERGENCIA para una pantalla que quedo negra. 'D' de DPMS.
-- Un 'dpms off' que NO haya disparado hypridle queda PEGADO: el 'on-resume' de
-- hypridle solo corre para el listener que efectivamente hizo timeout, asi que si
-- el apagado vino de otro lado (un hyprctl a mano, una prueba, un script) mover el
-- mouse no enciende nada y la unica salida era reiniciar el equipo. Este bind se
-- puede pulsar A CIEGAS con la pantalla apagada: el teclado le sigue llegando a
-- Hyprland aunque no haya senal de video.
-- OJO: el campo es 'action', NO 'state'. Con una clave desconocida el dispatcher cae
-- a TOGGLE (es el valor 0 del enum), o sea que dpms({ state = "on" }) APAGARIA una
-- pantalla encendida. Ver la explicacion larga en hypridle.conf.
hl.bind(mainMod .. " + D", hl.dsp.dpms({ action = "on" }))

-- Historial del portapapeles (cliphist): elegir una entrada con rofi y copiarla
hl.bind(secondMod .. " + V", hl.dsp.exec_cmd("cliphist list | rofi -dmenu -p 'Portapapeles' | cliphist decode | wl-copy"))

-- Selector de ventanas del workspace ACTUAL. Va a un script (bin_configs/pick-window)
-- y no a un 'rofi -show window' porque ese modo lista las ventanas de todos los
-- workspaces; el que filtraba por escritorio actual ('windowcd') no existe en el rofi
-- de Wayland. El script le pide la lista a Hyprland y usa rofi sólo como menú.
-- W de 'window'. La idea original era SUPER + ALT, pero no es viable: ALT es un
-- MODIFICADOR, y al pulsarlo Hyprland actualiza el estado de modificadores en vez de
-- mandarlo por el matcher de binds. Probado que no dispara ni como bind normal ni con
-- release = true (el 'bindr' de Hyprland, que engancha el soltar y es lo que suele
-- rescatar estos casos). Con una tecla normal funciona a la primera.
hl.bind(mainMod .. " + W", hl.dsp.exec_cmd("pick-window"))

-- Variante que lista TODOS los workspaces. Elegir una ventana de otro workspace salta
-- a ese workspace, restaura lo que estuviera maximizado y la enfoca: las tres cosas
-- las hace el dispatcher de foco de Hyprland solo, el script no las programa.
hl.bind(secondMod .. " + W", hl.dsp.exec_cmd("pick-window --all"))

-- Buscar un archivo en cualquier lugar de ~ y abrirlo con su aplicación por defecto.
-- F de 'find' / 'file', y queda al lado del Ctrl+F de zsh, que hace lo mismo dentro de
-- la terminal. SUPER + F estaba libre; SUPER + SHIFT + F (pantalla completa) no se toca.
--
-- El script (bin_configs/find-file) elige frontend solo: desde acá no hay terminal, así
-- que saca el menú de rofi; corrido a mano en una terminal saca fzf con preview.
hl.bind(mainMod .. " + F", hl.dsp.exec_cmd("find-file"))


-- Activar el submapa al pulsar Mod + R
hl.bind("SUPER + R", hl.dsp.submap("resize"))
-- Definición del submapa "resize"
hl.define_submap("resize", function()
  -- Ajustar tamaño de ventana activa (manteniendo presionado con repeating = true)
  hl.bind("L", hl.dsp.window.resize({ x = 10, y = 0, relative = true }), { repeating = true })
  hl.bind("H", hl.dsp.window.resize({ x = -10, y = 0, relative = true }), { repeating = true })
  hl.bind("I", hl.dsp.window.resize({ x = 0, y = -10, relative = true }), { repeating = true })
  hl.bind("J", hl.dsp.window.resize({ x = 0, y = 10, relative = true }), { repeating = true })

  -- Salir del submapa al presionar Enter o Escape
  hl.bind("Return", hl.dsp.submap("reset"))
  hl.bind("escape", hl.dsp.submap("reset"))
end)


-- Mover el WORKSPACE ACTIVO de una pantalla a otra. 'M' de monitor: SUPER + M
-- estaba libre (SUPER + SHIFT + M es apagar, esa no se toca).
--
-- Va en un submapa y no en un acorde por dos razones. La primera es que las
-- combinaciones direccionales ya estan las tres tomadas: SUPER mueve el foco,
-- SUPER + SHIFT mueve la ventana dentro del tiling y SUPER + CONTROL cambia de
-- workspace; lo que quedaba libre era SUPER + CONTROL + SHIFT, tres
-- modificadores para algo que se usa poco. La segunda es que el caso real no
-- es mover UN workspace: es enchufar el monitor y reacomodar dos o tres
-- seguidos. En el submapa se entra una vez y se sale con Esc.
--
-- Waybar ya muestra el submapa activo (modulo hyprland/submap), asi que no
-- hace falta ninguna notificacion extra para saber que uno esta adentro.
hl.bind(mainMod .. " + M", hl.dsp.submap("monitor"))

hl.define_submap("monitor", function()
  -- Las direcciones son las mismas que en el resto de la config: H/L para
  -- izquierda/derecha, I/K para arriba/abajo. Las flechas hacen exactamente lo
  -- mismo, asi no hay que acordarse de que aca "arriba" es I y no J.
  --
  -- El monitor se elige por DIRECCION (l/r/u/d) y no por indice relativo
  -- (+1/-1) porque el indice da la vuelta: en dos pantallas, empujar a la
  -- derecha desde la de la derecha te devolveria a la izquierda. Con la
  -- direccion no pasa nada y Hyprland avisa "Monitor not found", que es lo que
  -- uno espera al empujar contra el borde.
  --
  -- Sin 'workspace' en la tabla, el dispatcher usa el workspace activo.
  hl.bind("H", hl.dsp.workspace.move({ monitor = "l" }))
  hl.bind("L", hl.dsp.workspace.move({ monitor = "r" }))
  hl.bind("I", hl.dsp.workspace.move({ monitor = "u" }))
  hl.bind("K", hl.dsp.workspace.move({ monitor = "d" }))

  hl.bind("Left", hl.dsp.workspace.move({ monitor = "l" }))
  hl.bind("Right", hl.dsp.workspace.move({ monitor = "r" }))
  hl.bind("Up", hl.dsp.workspace.move({ monitor = "u" }))
  hl.bind("Down", hl.dsp.workspace.move({ monitor = "d" }))

  -- Salir del submapa al presionar Enter o Escape
  hl.bind("Return", hl.dsp.submap("reset"))
  hl.bind("escape", hl.dsp.submap("reset"))
end)

-- Switch workspaces with mainMod + [0-9]
-- Move active window to a workspace with mainMod + SHIFT + [0-9]
for i = 1, 10 do
  local key = i % 10 -- 10 maps to key 0
  hl.bind(mainMod .. " + " .. key, hl.dsp.focus({ workspace = i }))
  hl.bind(secondMod .. " + " .. key, hl.dsp.window.move({ workspace = i }))
end

-- Example special workspace (scratchpad)
hl.bind(mainMod .. " + S", hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))

-- Scroll through existing workspaces with mainMod + scroll
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Capturas de pantalla. Van en la tecla Print porque SUPER+S ya está tomado por el scratchpad "magic".
-- Los comandos están definidos arriba, en el bloque MY PROGRAMS.
hl.bind("Print", hl.dsp.exec_cmd(screenshot))                      -- región + anotar + portapapeles
hl.bind("SHIFT + Print", hl.dsp.exec_cmd(screenshotCopy))          -- región -> portapapeles
hl.bind("CONTROL + Print", hl.dsp.exec_cmd(screenshotSave))        -- región -> ~/Pictures + portapapeles
hl.bind("ALT + Print", hl.dsp.exec_cmd(screenshotWindow))          -- ventana activa -> portapapeles
hl.bind(mainMod .. " + Print", hl.dsp.exec_cmd(screenshotMonitor)) -- monitor completo -> portapapeles

-- Ayuda: referencia de atajos. 'A' de ayuda.
-- Se usa una LETRA a proposito: el layout de este equipo es latam, donde la barra
-- '/' no tiene tecla propia (se escribe con Shift+7), asi que un bind sobre el
-- keysym 'slash' no se dispara con la combinacion que uno esperaria. Las letras
-- estan en la misma posicion fisica en cualquier layout.
hl.bind(mainMod .. " + A", hl.dsp.exec_cmd(ayuda))

-- Tu nueva combinación base: SUPER + CONTROL
local thirdMod = mainMod .. " + CONTROL"

-- ==========================================
-- 1. CAMBIAR DE WORKSPACE (Navegación)
-- ==========================================

-- Moverse al espacio de trabajo ANTERIOR con 'H' (Izquierda)
hl.bind(thirdMod .. " + H", hl.dsp.focus({ workspace = "e-1" }))

-- Moverse al espacio de trabajo SIGUIENTE con 'L' (Derecha)
hl.bind(thirdMod .. " + L", hl.dsp.focus({ workspace = "e+1" }))

-- Opcionales (Vertical)
hl.bind(thirdMod .. " + K", hl.dsp.focus({ workspace = "e-1" })) -- Arriba / Anterior
hl.bind(thirdMod .. " + J", hl.dsp.focus({ workspace = "e+1" })) -- Abajo / Siguiente



-- Laptop multimedia keys for volume and LCD brightness
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"),
  { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),
  { locked = true, repeating = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),
  { locked = true, repeating = true })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),
  { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"), { locked = true, repeating = true })

-- Requires playerctl
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })


--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- See https://wiki.hypr.land/Configuring/Basics/Window-Rules/
-- and https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/

-- Example window rules that are useful

local suppressMaximizeRule = hl.window_rule({
  -- Ignore maximize requests from all apps. You'll probably like this.
  name           = "suppress-maximize-events",
  match          = { class = ".*" },

  suppress_event = "maximize",
})
-- suppressMaximizeRule:set_enabled(false)

hl.window_rule({
  -- Fix some dragging issues with XWayland
  name     = "fix-xwayland-drags",
  match    = {
    class      = "^$",
    title      = "^$",
    xwayland   = true,
    float      = true,
    fullscreen = false,
    pin        = false,
  },

  no_focus = true,
})

-- Layer rules also return a handle.
-- local overlayLayerRule = hl.layer_rule({
--     name  = "no-anim-overlay",
--     match = { namespace = "^my-overlay$" },
--     no_anim = true,
-- })
-- overlayLayerRule:set_enabled(false)

-- Hyprland-run windowrule
hl.window_rule({
  name  = "move-hyprland-run",
  match = { class = "hyprland-run" },

  move  = "20 monitor_h-120",
  float = true,
})

-- La ventana de ayuda (SUPER + A) sale flotante en vez de sumarse al mosaico.
hl.window_rule({
  name  = "ayuda-flotante",
  match = { title = "^ayuda-atajos$" },

  float = true,
})

-- Las TUI que abren los clics de Waybar (volumen, bluetooth, red, CPU, memoria) son
-- consultas puntuales que se cierran enseguida: salen flotantes para no reacomodar el
-- mosaico entero por una mirada de dos segundos.
--
-- El match va por TITULO y no por clase porque todas son la misma app (ghostty); lo
-- que las distingue es el '--title=' que les pasa cada on-click en waybar/config.jsonc.
-- Verificado que ese título sobrevive a la TUI: htop no lo pisa.
--
-- Sin 'center' ni 'size' a propósito: se deja que Hyprland las ubique y que cada una
-- conserve el tamaño que pide.
hl.window_rule({
  name  = "waybar-tui-flotantes",
  match = { title = "^(wiremix|bluetui|nmtui|htop|rclone-sync|rclone-log)$" },

  float = true,
})

-- btop va aparte porque necesita mucho más espacio que las otras: con el tamaño por
-- defecto de ghostty (800x600) se queja de que la terminal es chica y no dibuja sus
-- paneles.
--
-- OJO con el formato: 'size' sólo acepta una TABLA DE DOS NÚMEROS en píxeles lógicos.
-- Las variantes size = "80% 85%" y size = { "80%", "85%" } se aceptan sin error pero
-- NO hacen nada -- la ventana sale con el tamaño por defecto y uno no se entera.
-- Verificado probando las tres formas.
--
-- Píxeles lógicos (y no físicos) significa que el recuento de caracteres se mantiene
-- entre monitores con distinta escala, que es lo que le importa a btop.
hl.window_rule({
  name  = "btop-flotante-grande",
  match = { title = "^btop$" },

  float = true,
  size  = { 1024, 680 },
})
