return {
  "esmuellert/codediff.nvim",
  cmd = "CodeDiff",
  opts = {
    highlights = {
      line_insert = "DiffAdd",
      line_delete = "DiffDelete",
    },
    diff = {
      layout = "side-by-side",
      filler_text = "╱",
      disable_inlay_hints = true,
      max_computation_time_ms = 5000,
      ignore_trim_whitespace = false,
      hide_merge_artifacts = false,
      original_position = "left",
      cycle_next_hunk = true,
      cycle_next_file = true,
      jump_to_first_change = true,
      gutter_signs = false,
      compact_context_lines = 3,
      compact_sync_folds = true,
      compact = false,
    },
    explorer = {
      position = "left",
      hidden = false,
      width = 40,
      auto_refresh = true,
      indent_markers = true,
      initial_focus = "explorer",
      view_mode = "list",
      flatten_dirs = true,
      file_filter = {
        ignore = { ".git/**", ".jj/**" },
      },
      untracked = "all",
      focus_on_select = false,
      line_stats = {
        enabled = false,
        count_untracked = false,
      },
    },
    history = {
      position = "bottom",
      height = 15,
      initial_focus = "history",
      view_mode = "list",
      date_format = "%ar",
    },
    keymaps = {
      view = {
        quit = "q",
        toggle_explorer = "<leader>b",
        focus_explorer = "<leader>e",
        next_hunk = "]c",
        prev_hunk = "[c",
        next_file = "]f",
        prev_file = "[f",
        toggle_stage = "-",
        toggle_staged_view = "gS",
        stage_hunk = "<leader>hs",
        unstage_hunk = "<leader>hu",
        discard_hunk = "<leader>hr",
        hunk_textobject = "ih",
        show_help = "g?",
        toggle_layout = "t",
        toggle_compact = "gc",
      },
      explorer = {
        select = "<CR>",
        hover = "K",
        refresh = "R",
        toggle_view_mode = "i",
        stage_all = "S",
        unstage_all = "U",
        restore = "X",
        toggle_changes = "gu",
        toggle_staged = "gs",
      },
      conflict = {
        accept_incoming = "<leader>ct",
        accept_current = "<leader>co",
        accept_both = "<leader>cb",
        discard = "<leader>cx",
        accept_all_incoming = "<leader>cT",
        accept_all_current = "<leader>cO",
        accept_all_both = "<leader>cB",
        discard_all = "<leader>cX",
        next_conflict = "]x",
        prev_conflict = "[x",
      },
    },
  },
}
