vim.opt.nu=true
vim.opt.rnu=true
vim.opt.mouse="a"
vim.opt.tabstop=4
vim.opt.shiftwidth=4
vim.opt.expandtab=true
vim.opt.smartindent=true
vim.opt.clipboard="unnamed"
vim.opt.splitbelow=true
vim.opt.splitright=true
vim.g.mapleader=" "
vim.g.oscyank_term='default' -- needed for playing nicely with tmux
